### ISSUE TITLE
Error with PHPUnit 6.x

### ISSUE THREAD

**Issue by JeroenDeDauw** [whatthejeff/nyancat-phpunit-resultprinter#10]
> `>` vendor/bin/phpunit

> Fatal error: Class 'PHPUnit_TextUI_ResultPrinter' not found in /home/j/workspace/software.wikimedia.de/vendor/whatthejeff/nyancat-phpunit-resultprinter/src/NyanCat/PHPUnit/ResultPrinter.php on line 31
PHP Fatal error:  Class 'PHPUnit_TextUI_ResultPrinter' not found in /home/j/workspace/software.wikimedia.de/vendor/whatthejeff/nyancat-phpunit-resultprinter/src/NyanCat/PHPUnit/ResultPrinter.php on line 31

That is with PHPUnit ~6.0. ~5.7 works fine

**Comment by artjomsimon** [comment]
PHPUnit 6 dropped support for PHP < 7, that seems to be the only reason why the Travis build fails for the older versions.
@whatthejeff would you like to create a 2.x release for PHPUnit > 6, dropping support for PHP < 7 as well?
Thank you all for your work!
Would be a shame to let this die. This is too important.

**Comment by whatthejeff** [comment]
Just tagged v1.3.0 for PHPUnit 4/5 and v2.0.0 for PHPUnit 6. Thanks for your patience @artjomsimon and @JeroenDeDauw!

**Comment by artjomsimon** [comment]
Aaaw no, thank YOU! 👍 🌈

**Comment by JeroenDeDauw** [comment]
![image](https://cloud.githubusercontent.com/assets/146040/3205660/90e7a9b0-edb9-11e3-95c6-b4f47ed6e960.gif)
